import React from "react";
import { AlertTriangleIcon } from "../ui/Icons";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

// This component displays a single "Opportunity" item.
const OpportunityItem = ({ opportunity }) => {
  return (
    <div className="p-4 bg-[var(--insight-bg)] rounded-lg flex items-start gap-4 transition hover:bg-white/5">
      <div className="flex-shrink-0 w-6 h-6 mt-1">
        <AlertTriangleIcon className="text-amber-400" />
      </div>
      <div>
        <p className="font-bold text-[var(--text-primary)] flex items-center flex-wrap gap-2">
          {opportunity.title}
          {opportunity.savings && (
            <span className="text-xs font-mono bg-emerald-500/10 text-emerald-400 px-2 py-0.5 rounded-full">
              {opportunity.savings}
            </span>
          )}
        </p>

        {/* The className prop was removed from here. */}
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          components={{
            // The styles are now applied directly to the <p> tag generated by the Markdown.
            p: ({ node, ...props }) => (
              <p
                className="text-sm text-[var(--text-secondary)] break-words"
                {...props}
              />
            ),
          }}
        >
          {opportunity.description}
        </ReactMarkdown>
      </div>
    </div>
  );
};

export default OpportunityItem;
